### PR TITLE
Upgrade dependencies, test cases

### PR DESCRIPTION
**Pull request by ctjlewis**
Thanks for this fork!

[Build Status](https://travis-ci.com/ctjlewis/tonix-html-autoprefixer)

### CODE REVIEW

**Comment by tonix-tuft** [comment]
You are welcome, thank you for the PR! Do you confirm that your changes don't introduce any breaking changes to the JS API of this lib? I need to know it so that I will bump a new minor version of it featuring your changes and will publish it to NPM.

Let me know! Thanks!

**Comment by tonix-tuft** [comment]
Hello,

I checked your changes and they work. I published an updated version `2.1.0` to NPM. The only thing is that I kept my original package name `tonix-html-autoprefixer`:

https://www.npmjs.com/package/tonix-html-autoprefixer

Thank you again.

**Comment by ctjlewis** [comment]
You're welcome @tonix-tuft! I honestly don't remember anything about this PR—but one thing I noticed is my changes **included a change to the NPM package name** I think, can you confirm that's not a mistake and/or fix it with a new commit? Sorry about that if I included by accident.

**Comment by ctjlewis** [comment]
Oh, missed the second comment. Awesome, great work!

**Pull request merged**
